sudo: require
language: generic
services:
  - docker

before-install:
  - docker build -t mgad/docker-react ./frontend
  # - chmod +x ./scripts/build.sh
  # - chmod +x ./continous_deployment.sh

script:
  - docker run -e CI=true mgad/docker-react npm run test
  # - ./continous_deployment.sh
# notifications:
#   email: false
