sudo: require
language: generic
services:
  - docker

before-install:
  - docker build -t mgad/docker-react ./frontend
  # - chmod +x ./scripts/build.sh
  # - chmod +x ./continous_deployment.sh

script:
  - docker run -e CI=true mgad/docker-react npm run test
  - ./continous_deployment.sh

# before_deploy: "echo 'ready?'"
# deploy:
#   provider: heroku
#   api_key: ...
#   app:# my app
#     # master: my-app-staging
#     # production: my-app-production
#   on:
#     branch: master

# after_deploy:
# - ./after_deploy_1.sh
# - ./after_deploy_2.sh

notifications:
  email: false
# https://docs.travis-ci.com/user/deployment/heroku/

