#! /bin/bash

# docker build -t docker-heroku-simple .
heroku login
heroku container:login
heroku create my-app-v3
heroku addons:create mongolab --app=my-app-v3
read -p "Ready ?? "

heroku config:get MONGODB_URI --app=my-app-v3
read -p "Ready ?? "

heroku container:push --app=my-app-v3 web
heroku container:release --app=my-app-v3 web
heroku open --app=my-app-v3
heroku logs --tail --app=my-app-v3




# heroku apps:info





# read -p "Please, enter your name: "  VARNAME
# echo $VARNAME